$(init)
function init(){
    $('.video-kongbai-titlefirst').css('color','#6ba400');
        $('.video-kongbai-titlefirst').css('border-bottom-color','#6ba400');
	$('.video-tuijian1').show();
	$('.video-tuijian2').hide();
	$('.video-tuijian3').hide();
    $('.video-kongbai-titlefirst').click(function(){
        $('.video-tuijian1').show();
        $('.video-tuijian2').hide();
        $('.video-tuijian3').hide();
    });
    $('.video-kongbai-titlesecond').click(function(){
        $('.video-tuijian2').show();
        $('.video-tuijian1').hide();
        $('.video-tuijian3').hide();
    });
    $('.video-kongbai-titlethird').click(function(){
        $('.video-tuijian3').show();
        $('.video-tuijian2').hide();
        $('.video-tuijian1').hide();
    });

    $('.video-kongbai-titlefirst').click(function(){
        $('.video-kongbai-titlefirst').css('color','#6ba400');
        $('.video-kongbai-titlefirst').css('border-bottom-color','#6ba400');
        $('.video-kongbai-titlesecond').css('color','black');
        $('.video-kongbai-titlesecond').css('border-bottom-color','lightgrey');
        $('.video-kongbai-titlethird').css('color','black');
        $('.video-kongbai-titlethird').css('border-bottom-color','lightgrey');
    });
    $('.video-kongbai-titlesecond').click(function(){
        $('.video-kongbai-titlesecond').css('color','#6ba400');
        $('.video-kongbai-titlesecond').css('border-bottom-color','#6ba400');
        $('.video-kongbai-titlefirst').css('color','black');
        $('.video-kongbai-titlefirst').css('border-bottom-color','lightgrey');
        $('.video-kongbai-titlethird').css('color','black');
        $('.video-kongbai-titlethird').css('border-bottom-color','lightgrey');
    });
    $('.video-kongbai-titlethird').click(function(){
        $('.video-kongbai-titlethird').css('color','#6ba400');
        $('.video-kongbai-titlethird').css('border-bottom-color','#6ba400');
        $('.video-kongbai-titlesecond').css('color','black');
        $('.video-kongbai-titlesecond').css('border-bottom-color','lightgrey');
        $('.video-kongbai-titlefirst').css('color','black');
        $('.video-kongbai-titlefirst').css('border-bottom-color','lightgrey');
    });
}
